apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: devops-final
spec:
  replicas: 2
  selector:
    matchLabels: {app: devops-app}
  strategy:
    type: RollingUpdate
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
  template:
    metadata:
      labels: {app: devops-app}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: app
          image: ghcr.io/reaperxd67/devops-homework:latest
          imagePullPolicy: IfNotPresent
          ports: [{name: http, containerPort: 8080}]
          envFrom:
            - configMapRef: {name: app-config}
          env:
            - name: DEMO_TOKEN
              valueFrom:
                secretKeyRef: {name: app-secret, key: token}
          resources:
            requests: {cpu: 50m, memory: 32Mi}
            limits: {cpu: 250m, memory: 128Mi}
          startupProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet: {path: /readyz, port: http}
          livenessProbe:
            httpGet: {path: /healthz, port: http}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}
            seccompProfile: {type: RuntimeDefault}
          volumeMounts: [{name: temporary, mountPath: /tmp}]
      volumes: [{name: temporary, emptyDir: {}}]
